### ISSUE TITLE
Javascript ES6 Modules Highlighting different

### ISSUE THREAD

**Issue by jannikkeye** [liamsheppard/voodoo-theme#1]
First of all, I'm really digging this theme. The colors are great. But for me the javascript syntax highlighting seems a bit off. Copared it with your preview in the README. Check the image below.

Imports for example aren't highlighted properly and variables neither. Is the image in the README up to date?

![bildschirmfoto 2017-06-27 um 11 19 30](https://user-images.githubusercontent.com/10485074/27580348-936263c4-5b2a-11e7-9c2c-f84737ce73c1.png)

**Comment by liamsheppard** [comment]
Hi @jannikkeye !
It's great to hear that you're digging the theme, thanks!

I *have* updated the import syntax colouring since taking the photo for the Readme. I copied your file out on my machine and it looks like this:

![image](https://user-images.githubusercontent.com/15017759/27665138-cdb283a8-5cae-11e7-8161-9fcb8d0f79b0.png)

This looks like an old version of the theme to me (I'm a bit of a fiend when it comes to versions, sorry). The latest version is `0.3.13`, it looks like you might be running `0.3.8` or around there.

If you are in fact running the latest version though, let me know and we'll try something else!

**Comment by jannikkeye** [comment]
@liamsheppard thanks for the response :) I am indeed running 0.3.13. I'm gonna check if there are any intereferences with other packages.
